language: c

addons:
  apt:
    packages:
      - cmake
      - libgsl0-dev
      - libfftw3-dev
  homebrew:
    packages:
      - cmake
      - pkgconfig
      - gsl
      - fftw

matrix:
  include:
    - os: linux
      name: "GNU/Linux with GCC"
    - os: osx
      name: "macOS with AppleClang"
      osx_image: xcode10.2

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - make install
    - ctest -vv
